services:
  # Backend API Service
  - type: web
    name: sales-analytics-backend
    env: python
    region: frankfurt
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
  
  # Frontend Static Site
  - type: web
    name: sales-analytics-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

databases:
  # PostgreSQL Database for Production
  - name: sales-analytics-db
    databaseName: sales_analytics
    user: sales_analytics_user
    region: frankfurt
    plan: free
